export const runtime = 'edge';
export { proxy as middleware } from './middlewareHandler';

export const config = {
  matcher: [
    '/eurovision1955/:path*',
    '/api/votes/:year/simple/:path*',
    '/api/votes/:year/public/:path*',
    '/api/config/vote-config',
    '/api/admin/config',
    '/admin',
    '/admin/:path*',
    '/debug',
    '/debug/:path*',
    '/eurovision2020',
    '/eurovision2021',
    '/eurovision2022',
    '/eurovision2023',
    '/eurovision2024',
    '/eurovision2025',
    '/eurovision2026',
    '/eurovision2020/:path*',
    '/eurovision2021/:path*',
    '/eurovision2022/:path*',
    '/eurovision2023/:path*',
    '/eurovision2024/:path*',
    '/eurovision2025/:path*',
    '/eurovision2026/:path*',
    '/eurovision2020/vote/:path*',
    '/eurovision2020/voting/:path*',
    '/eurovision2021/vote/:path*',
    '/eurovision2021/voting/:path*',
    '/eurovision2022/vote/:path*',
    '/eurovision2022/voting/:path*',
    '/eurovision2023/vote/:path*',
    '/eurovision2023/voting/:path*',
    '/eurovision2024/vote/:path*',
    '/eurovision2024/voting/:path*',
    '/eurovision2025/vote/:path*',
    '/eurovision2025/voting/:path*',
    '/eurovision2026/vote/:path*',
    '/eurovision2026/voting/:path*',
  ],
};
